build:
  environment:
    php: 7.2.24
    timezone: Europe/Paris

  nodes:
    tests:
      tests:
        override:
          - command: composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover
